#!/bin/bash

# Colors for Bash using Base16 Shell
# (https://github.com/chriskempson/base16-shell)
#
# This script is a simplified version of the original profile_helper.sh for Bash 

BASE16_SHELL="${HOME}/.bash.d/base16-shell-schemes"
BASE16_THEME="base16-default-dark"

script="${BASE16_SHELL}/${BASE16_THEME}.sh"
if [ -f "${script}" ]; then
#	export BASE16_THEME
	source "${script}"
#	if [ -n "${BASE16_SHELL_HOOKS:+s}" ] && [ -d "${BASE16_SHELL_HOOKS}" ]; then
#		for hook in ${BASE16_SHELL_HOOKS}/*; do
#			[ -f "${hook}" ] && [ -x "${hook}" ] && "${hook}"
#		done
#	fi
fi

unset BASE16_SHELL
unset BASE16_THEME
