#!/bin/bash

exitstatus()
{
	if [[ $? == 0 ]]; then
		echo ':)';
	else
		echo ':(';
	fi
}

## Text format
bold="\033[1m"
reset="\033[0m"

## Text colours
## To see the full range of supported colours:
##   for c in {0..255}; do printf "\033[38;5;%sm %s \033[0m" $c $c; done; echo;
# Default colors
blue="\033[34m"
gray="\033[90m"
green="\033[32m"
red="\033[31m"
magenta="\033[35m"
# Colours for base16-default-dark with 256 colours support
#blue="\033[38;5;33m"
#gray="\033[38;5;8m"
#green="\033[38;5;34m"
#red="\033[38;5;124m"
#magenta="\033[38;5;62m"

## Highlight the user name when logged in as root
if [[ "${USER}" == "root" ]]; then
	userStyle="${bold}${red}";
else
	userStyle="${blue}";
fi;

## Highlight the hostname when connected via SSH
if [[ "${SSH_TTY}" ]]; then
	hostStyle="${bold}${red}";
else
	hostStyle="${magenta}";
fi;

## Set the terminal prompt
PS1="\[${userStyle}\]\u"             # username
PS1+="\[${gray}\]@"
PS1+="\[${hostStyle}\]\h"            # host
PS1+="\[${gray}\]:"
PS1+="\[${green}\]\W"                # working directory
PS1+="\[${reset}\] \$(exitstatus) "  # status of last executed command
export PS1

unset bold
unset reset
unset blue
unset gray
unset green
unset red
unset magenta
unset userStyle
unset hostStyle 
