#!/bin/sh

# Colours for ls
if ls --color > /dev/null 2>&1; then
	export LS_COLORS="di=34:ln=35:so=31:pi=33:ex=32:bd=30;46:cd=0;45:su=33;42:sg=33;42:tw=31;44:ow=0;44"
else
	export LSCOLORS="exfxbxdxcxagxfdcdcbexe"
fi

# Colours for shell - Tinted Shell (https://github.com/tinted-theming/tinted-shell)
export COLOR_THEME="base16-default-dark"
script="$HOME/.config/shell/tinted-shell/scripts/$COLOR_THEME.sh"
[ -f "$script" ] && [ -r "$script" ] && . "$script"
unset script
