#!/bin/sh

# Load the corresponding configuration files if using particular shells
if [ -n "$BASH" ]; then
	[ -r "$HOME/.config/bash/bashrc" ] && . "$HOME/.config/bash/bashrc"
	return
fi

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

for script in $HOME/.config/shell/shinit.d/*; do
	[ -r "$script" ] && . "$script"
done
unset script

