#!/bin/sh

script="$HOME/.config/shell/aliases"
[ -f "$script" ] && [ -r "$script" ] && . "$script"

script="$HOME/.config/shell/colours"
[ -f "$script" ] && [ -r "$script" ] && . "$script"

case $0 in
*bash*)
	script="$HOME/.config/bash/prompt" ;;
*)
	script="$HOME/.config/shell/prompt" ;;
esac
[ -f "$script" ] && [ -r "$script" ] && . "$script"

unset script
