#!/bin/sh

## Load the corresponding configuration files for some shells
if [ -n "$BASH" ]; then
	script="$HOME/.config/bash/bashrc"
	[ -f "$script" ] && [ -r "$script" ] && . "$script"
	unset script
	return
fi

## General shell configuration
for script in "$HOME"/.config/shell/shinit.d/*; do
	[ -f "$script" ] && [ -r "$script" ] && . "$script"
done
unset script

