" Pathogen
source ~/.vim/bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect('~/.vim/bundle/{}')

" Make Vim behave in a more useful way
set nocompatible

" Enable file type detection and loading plugin files
filetype plugin on

" Enable sytax highlight
syntax on

" Enable line numbers
set number

" Use relative line numbers
set relativenumber

" Highlight current line
set cursorline

" Always show status line
set laststatus=2

" Show the cursor position
set ruler

" Configure backspace
set backspace=indent,eol,start

"Splits
"
" Open splits at the bottom and right
set splitbelow splitright
" Split navigation
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" Plugin: Base16 Vim
"         (https://github.com/chriskempson/base16-vim)
"
" base16colorspace
" (see https://github.com/chriskempson/base16-vim#256-colorspace)
let base16colorspace=256

" Colorscheme
colorscheme base16-default-dark

" Plugin: vim-latex
"         (http://vim-latex.sourceforge.net)
"
" Change default empty .tex file type from 'plaintex' to 'tex'
" (see http://vim-latex.sourceforge.net/documentation/latex-suite/recommended-settings.html)
let g:tex_flavor='latex'
" Change default <C-j> for placeholders (it conflicts with split navigation)
" (see http://vim-latex.sourceforge.net/documentation/latex-suite/latex-suite-maps.html)
imap <Nul> <Plug>IMAP_JumpForward
nmap <Nul> <Plug>IMAP_JumpForward
vmap <Nul> <Plug>IMAP_JumpForward
