set nocompatible

set viminfo+=n~/.config/vim/viminfo

filetype plugin indent on

set autoindent
set smartindent

set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab

set backspace=indent,eol,start

set ignorecase
set smartcase
set incsearch

set scrolloff=4

set splitbelow splitright

set wildmenu

" Pathogen
source ~/.config/vim/bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect('~/.config/vim/bundle/{}')

"-------------------------------------------------------------------------------
" Visual settings
"-------------------------------------------------------------------------------

syntax on

set number
set relativenumber
set cursorline
"set colorcolumn=80

set laststatus=2
set ruler

" My version of base16-default-dark (see colors/base16-default-dark.vim)
colorscheme base16-default-dark

"-------------------------------------------------------------------------------
" Key mappings
"-------------------------------------------------------------------------------

let mapleader="\<space>"

" Open netrw with <leader>cd
nnoremap <leader>cd :Ex<CR>

" Split navigation
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

"-------------------------------------------------------------------------------
" Plugin: lsp
"         (https://github.com/yegappan/lsp)
"-------------------------------------------------------------------------------

let lspOptions = #{
    \ autoHighlight: v:true,
    \ diagSignErrorText: '✘',
    \ diagSignHintText: '⚑',
    \ diagSignInfoText: '»',
    \ diagSignWarningText: '▲',
    \ noNewlineInCompletion: v:true,
    \ outlineOnRight: v:true,
    \ outlineWinSize: 70,
    \ semanticHighlight: v:true,
    \ showDiagOnStatusLine: v:true,
\ }
autocmd User LspSetup call LspOptionsSet(lspOptions)

let lspServers = [
    \ #{
        \ name: 'bash-language-server',
        \ filetype: ['sh'],
        \ path: 'bash-language-server',
        \ args: ['start'],
    \ },
    \ #{
        \ name: 'clangd',
        \ filetype: ['c', 'cpp'],
        \ path: 'clangd',
        \ args: ['--background-index']
    \ },
    \ #{
        \ name: 'rust-analyzer',
        \ filetype: ['rust'],
        \ path: 'rust-analyzer',
        \ args: [],
        \ syncInit: v:true,
    \ },
\ ]
autocmd User LspSetup call LspAddServer(lspServers)

" Highlight customisation
hi LspDiagInlineError ctermfg=black ctermbg=red
hi LspDiagInlineWarning ctermfg=black ctermbg=yellow
hi LspDiagInlineInfo cterm=underline
hi LspDiagInlineHint ctermfg=black ctermbg=cyan
hi LspDiagSignErrorText ctermfg=red ctermbg=18
hi LspDiagSignWarningText ctermfg=yellow ctermbg=18
hi LspDiagSignInfoText ctermfg=blue ctermbg=18
hi LspDiagSignHintText ctermfg=cyan ctermbg=18
hi link LspInlayHintsParam LineNr
hi link LspInlayHintsType LineNr
" Highlight customisation - Not documented
hi LspTextRef ctermbg=19
hi LspReadRef ctermbg=19
hi LspWriteRef ctermbg=19

" Enable auto selection of the fist autocomplete item
augroup LspSetup
    au!
    au User LspAttached set completeopt-=noselect
augroup END

" Key mappings for most-used functions
nnoremap <leader>o :LspDocumentSymbol<CR>
nnoremap <leader>i :LspHover<CR>
nnoremap <leader>gd :LspGotoDefinition<CR>
nnoremap <leader>pd :LspPeekDefinition<CR>
nnoremap <leader>h :LspInlayHints toggle<CR>
nnoremap <leader>r :LspRename<CR>
nnoremap <leader>R :LspPeekReferences<CR>

"-------------------------------------------------------------------------------
" Plugin: vimtex
"         (https://github.com/lervag/vimtex)
"-------------------------------------------------------------------------------
" Change default .tex file type from 'plaintex' to 'tex'
" (see https://github.com/lervag/vimtex/wiki/introduction#comment-on-internal-tex-plugin)
let g:tex_flavor='latex'
let g:vimtex_view_method='zathura'
