set nocompatible

" Pathogen
source ~/.vim/bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect('~/.vim/bundle/{}')

set viminfo='50,<50,s50,/0,:0,h,n~/.vim/viminfo

set path+=**

filetype plugin on

syntax on

set backspace=indent,eol,start

set incsearch

set wildmenu

set number
set relativenumber
set cursorline

set laststatus=2
set ruler

set splitbelow splitright
" Split navigation
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" Plugin: Base16 Vim
"         (https://github.com/chriskempson/base16-vim)
"
if !empty($BASE16_THEME)
"	(see https://github.com/chriskempson/base16-vim#256-colorspace)
	let base16colorspace=256
	colorscheme $BASE16_THEME
	" base16-vim resets the syntax
	hi CursorLineNr cterm=bold
endif

" Plugin: UltiSnips
"         (https://github.com/SirVer/ultisnips)
"
let g:UltiSnipsEditSplit='vertical'
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<tab>"
let g:UltiSnipsJumpBackwardTrigger="<s-tab>"

" Plugin: vimtex
"         (https://github.com/lervag/vimtex)
"
" Change default .tex file type from 'plaintex' to 'tex'
" (see https://github.com/lervag/vimtex/wiki/introduction#comment-on-internal-tex-plugin)
let g:tex_flavor='latex'
