#!/bin/sh

## Keyboard

setxkbmap -model dell -layout us -variant altgr-intl

## Display

DISPLAY_NAME=eDP-1
DISPLAY_MODE=1920x1080
DISPLAY_RATE=60
DISPLAY_DPI=96

case $GRAPHICS_OFFLOAD in
	PRIME)
		DISPLAY_NAME=eDP-1-1
		xrandr --setprovideroutputsource modesetting NVIDIA-0
		;;
	*)
		;;
esac

xrandr --output "$DISPLAY_NAME" --mode "$DISPLAY_MODE" --rate "$DISPLAY_RATE" --primary
xrandr --dpi "$DISPLAY_DPI"

