#!/bin/sh

#[ -f "/etc/X11/xinit/.Xresources" ] xrdb -merge "/etc/X11/xinit/.Xresources"

#[ -f "/etc/X11/xinit/.Xmodmap" ] && xmodmap "/etc/X11/xinit/.Xmodmap"

[ -f "$HOME/.config/X11/Xresources" ] && xrdb -merge "$HOME/.config/X11/Xresources"

#[ -f "$HOME/.Xmodmap" ] && xmodmap "$HOME/.Xmodmap"

if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
		[ -x "$f" ] && . "$f"
	done
fi

## Keyboard

setxkbmap -layout es,gb -model apple_laptop, -option grp:shifts_toggle

## Display

DISPLAY_NAME=LVDS-1
DISPLAY_MODE=1280x800
DISPLAY_RATE=60
DISPLAY_DPI=96

xrandr --output "$DISPLAY_NAME" --mode "$DISPLAY_MODE" --rate "$DISPLAY_RATE" --primary
xrandr --dpi "$DISPLAY_DPI"

xcalib "$HOME/.config/color/icc/ColorLCD-CB5A19E1-6C20-C98E-BB2D-70FC3BB550B4.icc"

# Make sure the optical audio is off
amixer -q -c 0 set 'IEC958',16 mute

dunst &

if ! which systemctl >/dev/null; then
	pipewire &
	pipewire-pulse &
	pipewire-media-session &
fi

exec dwm
