#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
		[ -x "$f" ] && . "$f"
	done
fi

[ -f "$HOME/.config/X11/Xresources" ] && xrdb -merge "$HOME/.config/X11/Xresources"

## Keyboard

setxkbmap -layout us,gb -model dell, -variant altgr-intl, -option grp:shifts_toggle

## Display

DISPLAY_NAME=eDP-1
DISPLAY_MODE=1920x1080
DISPLAY_RATE=60
DISPLAY_DPI=96

if [ "$(xrandr --listproviders | awk '/Provider 0/ {print $NF}')" = "name:NVIDIA-0" ]; then
	DISPLAY_NAME=eDP-1-1
	xrandr --setprovideroutputsource modesetting NVIDIA-0
fi

xrandr --dpi "$DISPLAY_DPI" --output "$DISPLAY_NAME" --auto --primary

## SSH agent (SSH_AUTH_SOCK, SSH_AGENT_PID)

script="$XDG_RUNTIME_DIR/ssh-agent.env"
! pgrep -u "$USER" ssh-agent > /dev/null && ssh-agent > "$script"
[ ! -f "$SSH_AUTH_SOCK" ] && . "$script" > /dev/null

## Various programs

dunst &

dwmblocks &

exec dwm
