#!/bin/bash

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

script="$HOME/.config/shell/shinit.d/aliases"
[ -r "$script" ] && . "$script"
script="$HOME/.config/shell/shinit.d/colours"
[ -r "$script" ] && . "$script"
script="$HOME/.config/bash/bashrc.d/prompt"
[ -r "$script" ] && . "$script"

unset script

