#!/bin/sh

script="$HOME/.config/shell/aliases"
[ -f "$script" ] && [ -r "$script" ] && . "$script"
script="$HOME/.config/shell/colours"
[ -f "$script" ] && [ -r "$script" ] && . "$script"
script="$HOME/.config/bash/prompt"
[ -f "$script" ] && [ -r "$script" ] && . "$script"
unset script
