#!/bin/bash

# Colours for `ls`
if ls --color > /dev/null 2>&1; then
	export LS_COLORS="di=34:ln=35:so=31:pi=33:ex=32:bd=30;46:cd=0;45:su=33;42:sg=33;42:tw=31;44:ow=0;44"
else
	export LSCOLORS="exfxbxdxcxagxfdcdcbexe"
fi

# Colours for Bash - Base16 Shell (https://github.com/chriskempson/base16-shell)
# These lines are taken from profile_helper.sh 
# Theme to use
BASE16_THEME="base16-default-dark"
# Location of base16-shell
BASE16_SHELL="$HOME/.config/bash/base16-shell"
# Apply theme
script="$BASE16_SHELL/scripts/$BASE16_THEME.sh"
[ -r "$script" ] && [ -f "$script" ] && . "$script"

unset BASE16_THEME
unset BASE16_SHELL
unset script

