#!/bin/bash

exitstatus() { if [ $? -eq 0 ]; then echo ":)"; else echo ":("; fi }

# Text format
bold="\033[1m"
reset="\033[0m"

# Text colours
#
# To see the full range of supported colours:
#
#     for c in {0..255}; do printf "\033[38;5;%sm %s \033[0m" $c $c; done; echo;
#
# Default colours
blue="\033[34m"
gray="\033[90m"
green="\033[32m"
red="\033[31m"
magenta="\033[35m"

# Highlight the user name when logged in as root
if [ "$USER" = "root" ]; then
	user="\[$bold$red\]\u\[$reset\]";
else
	user="\[$blue\]\u\[$reset\]";
fi;

# Highlight the hostname when connected via SSH
if [ "$SSH_TTY" ]; then
	host="\[$bold$red\]\h\[$reset\]";
else
	host="\[$magenta\]\h\[$reset\]";
fi;

## Set the terminal prompt
#  user@host:dir stat_last_cmd
export PS1="$user\[$gray\]@$host\[$gray\]:\[$green\]\W\[$reset\] \$(exitstatus) "

unset bold
unset reset
unset blue
unset gray
unset green
unset red
unset magenta
unset user
unset host

