#!/bin/sh

# Get data of connected monitors from xrandr
_XRANDR_DATA=$(xrandr | sed -e "/disconnected/,$ d")
# Get connected monitors and their data
_MON_CONN_DATA=$(echo "$_XRANDR_DATA" | grep "connected")
# Get connected monitors
_MON_CONN=$(echo "$_MON_CONN_DATA" | awk '{print $1}')
# Get number of connected monitors
_MON_N=$(echo "$_MON_CONN" | wc -l)

dmenu_sel_chk()
{
	_SEL=$(echo -e "$1" | dmenu -i -p "$2")
	if [ -z "$_SEL" ] || [ ! $(echo "$1" | grep "$_SEL") ]; then
		exit 1
	fi
}

mon_get_curres()
{
	echo "$(echo "$_XRANDR_DATA" | sed -e "1,/$1/ d" -e "/connected/,$ d" | grep "*" | awk '{print $1}')"
}

mon_get_prefres()
{
	echo "$(echo "$_XRANDR_DATA" | sed -e "1,/$1/ d" -e "/connected/,$ d" | grep "+" | awk '{print $1}')"
}

extend()
{
	# Select primary monitor
	dmenu_sel_chk "$_MON_CONN" "Select primary monitor:"
	mon_pri=$_SEL
	# Get second monitor and select its position respect to primary monitor
	mon_sec=$(echo "$_MON_CONN" | grep -v "$mon_pri")
	dmenu_sel_chk "left\nright\nabove\nbelow" "Position of $mon_sec relative to $mon_pri:"
	if [ "$_SEL" = "left" ] || [ "$_SEL" = "right" ]; then
		mon_sec_pos=$_SEL"-of"
	else
		mon_sec_pos=$_SEL
	fi
	# Get current resolution of monitors, or the preferred ones if the
	# monitors are not enabled
	mon_pri_res=$(mon_get_curres "$mon_pri")
	if [ -z "$mon_pri_res" ]; then
		mon_pri_res=$(mon_get_prefres "$mon_pri")
	fi
	mon_sec_res=$(mon_get_curres "$mon_sec")
	if [ -z "$mon_sec_res" ]; then
		mon_sec_res=$(mon_get_prefres "$mon_sec")
	fi
	# Extend monitor
	xrandr --output "$mon_pri" --primary --mode "$mon_pri_res" --scale 1.0x1.0\
               --output "$mon_sec" --mode "$mon_sec_res" --scale 1.0x1.0 --"$mon_sec_pos" "$mon_pri"
}

mirror()
{
	# Select primary monitor
	dmenu_sel_chk "$_MON_CONN" "Select main monitor:"
	mon_pri=$_SEL
	# Get second monitor
	mon_sec=$(echo "$_MON_CONN" | grep -v "$mon_pri")
	# Get current resolution of main monitor, or the preferred one if it is
	# not enabled, and the preferred resolution for second monitor
	mon_pri_res=$(mon_get_curres "$mon_pri")
	if [ -z "$mon_pri_res" ]; then
		mon_pri_res=$(mon_get_prefres "$mon_pri")
	fi
	mon_sec_res=$(mon_get_prefres "$mon_sec")
	# Get scale ratios
	mon_pri_w=$(echo "$mon_pri_res" | awk -F 'x' '{print $1}')
	mon_pri_h=$(echo "$mon_pri_res" | awk -F 'x' '{print $2}')
	mon_sec_w=$(echo "$mon_sec_res" | awk -F 'x' '{print $1}')
	mon_sec_h=$(echo "$mon_sec_res" | awk -F 'x' '{print $2}')
	scale_x=$(echo "$mon_pri_w / $mon_sec_w" | bc -l)
	scale_y=$(echo "$mon_pri_h / $mon_sec_h" | bc -l)
	# Mirror monitor
	xrandr --output "$mon_pri" --primary --mode "$mon_pri_res" --scale 1.0x1.0 \
               --output "$mon_sec" --auto --same-as "$mon_pri" --scale "$scale_x"x"$scale_y"
}

case "$_MON_N" in
2)
	action=$(echo -e "Extend monitor\nMirror monitor" | dmenu -i -p "Select action:")
	case "$action" in
	"Extend monitor")
		extend ;;
	"Mirror monitor")
		mirror ;;
	*)
		exit 1 ;;
	esac
	;;
*)
	exit
	;;
esac
