#!/bin/sh

# Get all connected screens
aux=$(xrandr)
conn=$(echo "${aux}" | grep " connected ")
nscr=$(echo "${conn}" | wc -l)

if [ ${nscr} -eq 0 ]; then
	exit
fi

action=$(echo -e "Connect external monitor\nChange resolution" | dmenu -i -p "Select action:")
case ${action} in

"Connect external monitor")

	prim=$(echo "${conn}" | grep "primary" | awk '{print $1}')
	conn=$(echo "${conn}" | grep -v ${prim} | awk '{print $1}')
	# Get new screen
	case ${nscr} in
	1)
		exit
		;;
	2)
		new=${conn}
		;;
	*)
		new=$(echo "${conn}" | dmenu -i -p "Select monitor:")
		[ -z ${new} ] && exit
		[ -z $(echo "${conn}" | grep ${new}) ] && exit
		;;
	esac
	# Set position
	pos=$(echo -e "left\nright" | dmenu -i -p "Should ${new} be placed left or right of ${prim}?")
	case ${pos} in
	left | right)
		xrandr --output "${prim}" --auto --output "${new}" --"${pos}"-of "${prim}" --auto
		;;
	*)
		;;
	esac
	;;

"Change resolution")

	conn=$(echo "${conn}" | awk '{print $1}')
	# Get screen
	case ${nscr} in
	1)
		scr=${conn}
		;;
	*)
		scr=$(echo "${conn}" | dmenu -i -p "Select monitor:")
		[ -z ${scr} ] && exit
		[ -z $(echo "${conn}" | grep ${scr}) ] && exit
		;;
	esac
	# Select and set resolution
	aux=$(echo "${aux}" | sed -e "1,/${scr}/ d" -e "/connected/,$ d" | awk '{print $1}')
	res=$(echo "${aux}" | dmenu -i -p "Select resolution for ${scr}:")
	[ -z ${res} ] && exit
	[ -z $(echo "${aux}" | grep ${res}) ] && exit
	xrandr --output "${scr}" --mode "${res}"
	;;

*)
	;;

esac
